export enum EIconTypes {
  HEART = 'HEART',
  HEART_SOLID = 'HEART_SOLID',
  HOME = 'HOME',
  INFO = 'INFO',
  SEARCH = 'SEARCH',
  CROSS = 'CROSS',
  COMMENT_CHECK = 'COMMENT_CHECK',
  PLUS_CIRCLE = 'PLUS_CIRCLE',
  LANDSCAPE = 'LANDSCAPE',
  APPS_ADD = 'APPS_ADD',
  CHECK = 'CHECK',
  HARD = 'HARD',
}
