name: Build and Lint

on:
  push:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Format code
        run: yarn format

      - name: Build
        run: yarn build

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/recode-web-platform:1.2 .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Registry
        run: docker push ${{ secrets.DOCKER_USERNAME }}/recode-web-platform:1.2

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/recode-web-platform:1.2
            if [ "$(sudo docker ps -a -q)" ]
            then 
              sudo docker stop $(docker ps -a -q) 
              sudo docker rm $(docker ps -a -q) 
            fi
            sudo docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/recode-web-platform:1.2
 
